### ISSUE TITLE
PackagesNotFoundError

### ISSUE THREAD

**Issue by danischles** [NSLS-II/PyXRF#120]
I tried to follow the install for Mac using conda, and keep getting the following error after trying to type this command line:
PyXRF-master danielleschlesinger$ conda install pyxrf pyqt=4.11 enaml=0.9.8 -c lightsource2-tag

error message:

Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pyxrf
  - scikit-beam

Current channels:

  - https://conda.anaconda.org/lightsource2-tag/osx-64
  - https://conda.anaconda.org/lightsource2-tag/noarch
  - https://repo.continuum.io/pkgs/main/osx-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch

**Comment by licode** [comment]
Please try the following after you create an env at python3.5.
```
conda install pyxrf pyqt=4.11 -c lightsource2-tag -c conda-forge
```

**Comment by danischles** [comment]
thank you, it worked!
