### ISSUE TITLE
The number of detector channels is incorrectly determined by make_hdf() on SRX beamline data

### ISSUE THREAD

**Issue by dmgav** [NSLS-II/PyXRF#167]
The number of channels is incorrectly determined by the function hake_hdf() while generating HDF files from database data (SRX beamline). Invalid assumptions on the meaning of start document metadata result in 3-channel scans interpreted as 1-channel scans.

**Comment by andrewmkiss** [comment]
Scan type has been fixed in the start document. Update has been pushed to github.

**Comment by dmgav** [comment]
The issue is fixed in PR https://github.com/NSLS-II/PyXRF/pull/174
