### ISSUE TITLE
Calculating concentration from ED-XRF data

### ISSUE THREAD

**Issue by Chris-Has** [NSLS-II/PyXRF#224]
Hi 
I couldn't find a way to contact anyone on your team directly so apologies for logging it as an issue and I couldn't access your publication through my institution to find out more.

I'd like to know if I can use this program for determining elemental concentration from ED-XRF spectra?

Cheers
Chris

**Comment by dmgav** [comment]
Hi Chris,

Thank you for interest in PyXRF. The program was developed primarily for processing of scanned XRF maps from NSLS-II imaging beamlines. There are some quantitative analysis features implemented. It could probably be adapted for different type of XRF experiments as well. PyXRF GUI is currently being rewritten so it is expected to work better. If you give us your email, we can email you the publication.

Regards,
Dmitri.

**Comment by Chris-Has** [comment]
Thanks Dmitri. I'll give it a try.
Please email the publication to chrisdh08@gmail.com
That would be greatly appreciated. Thanks

CHris
