### ISSUE TITLE
Issue with new ipython 4.0.0

### ISSUE THREAD

**Issue by licode** [NSLS-II/PyXRF#50]
Stable at ipython version 3.2.0. Some conflicts with lmfit.

**Comment by ericdill** [comment]
What are these issues?

**Comment by licode** [comment]
something like this if using ipython4.0.0. I downgrade ipython to 3.2.0, then it works fine.
https://gist.github.com/licode/32b8503976d150f80773

**Comment by ericdill** [comment]
try to `conda install ipywidgets` with IPython 4.0.0

**Comment by licode** [comment]
But can we find ipywidgets for mac? I can do that for linux.

**Comment by ericdill** [comment]
Yes, ipywidgets exists for mac. I just installed ipython=4 and ipywidgets
