### ISSUE TITLE
user should be about to Save to tiff on fitted data without performing fitting again

### ISSUE THREAD

**Issue by imrealkaren** [NSLS-II/PyXRF#72]
Users should be able to perform "Save to tiff" and "Save to txt' functions on fitted data with performing the fitting again
Once the fitting is performed, the fitted data is in the hdf5 file and users should be able to output the fitting results without performing the fitting again

Perhaps the functions can be moved from 'Fit' to 'File IO'?

**Comment by licode** [comment]
This is already implemented. Users do not need to do fitting again in order to save data. It is a good idea to think about a better fileIO interface to include those saving functions.

**Comment by imrealkaren** [comment]
Thanks! It works for now.

**Comment by imrealkaren** [comment]
although the output folder name is not correct.
I have output a file named: 2015_10_25_20_28_pyxrf_fit and the folder is named: "2015_10_output" which is a problem as we have multiple files start with 2015_10.

**Comment by licode** [comment]
ok. I will fix that.

**Comment by licode** [comment]
Issue should be resolved. Restart pyxrf at beamline machine and try it.
