### ISSUE TITLE
conflicts with QApplication in Linux

### ISSUE THREAD

**Issue by licode** [NSLS-II/PyXRF#77]
In [2]: from pyxrf.model.fit_spectrum import *
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-56a69382b62f> in <module>()
----> 1 from pyxrf.model.fit_spectrum import *

/nfs/xf05id1/src/git_li/PyXRF/pyxrf/model/fit_spectrum.py in <module>()
     50 from scipy.interpolate import interp1d, interp2d
     51 
---> 52 from enaml.qt.qt_application import QApplication
     53 
     54 from atom.api import Atom, Str, observe, Typed, Int, List, Dict, Float, Bool

/home/xf05id1/conda_envs/pyxrf/lib/python2.7/site-packages/enaml-0.9.8-py2.7-linux-x86_64.egg/enaml/qt/__init__.py in <module>()
     26     try:
     27         import PyQt4
---> 28         prepare_pyqt()
     29         QT_API = os.environ['QT_API'] = 'pyqt'
     30     except ImportError:

/home/xf05id1/conda_envs/pyxrf/lib/python2.7/site-packages/enaml-0.9.8-py2.7-linux-x86_64.egg/enaml/qt/__init__.py in prepare_pyqt()
     11 def prepare_pyqt():
     12     import sip
---> 13     sip.setapi('QDate', 2)
     14     sip.setapi('QDateTime', 2)
     15     sip.setapi('QString', 2)

ValueError: API 'QDate' has already been set to version 1

**Comment by licode** [comment]
Looks like I can't import from ipython if QApplication is used. This only happens in Linux. Better idea @ericdill @tacaswell ?

**Comment by ericdill** [comment]
What happens if your first import is 

```python
from enaml.qt.qt_application import QApplication
```

**Comment by ericdill** [comment]
and then you try:

```python
from pyxrf.model.fit_spectrum import *
```

**Comment by tacaswell** [comment]
The issue is that something else is importing Qt first with a less aggressive set of API versions.  Make sure IPython is not importing matplotlib automatically on import.

**Comment by licode** [comment]
neat. It works fine if I import QApplication first. Thanks, folks.
