### ISSUE TITLE
create movie in linux

### ISSUE THREAD

**Issue by licode** [NSLS-II/PyXRF#78]
Here is an example I tried to create a movie on linux. Everything works fine on mac.

```
import matplotlib.pyplot as plt
import numpy as np
import tomopy
#from evtk.hl import *
import matplotlib.animation as animation

def ani_frame():
    dpi = 100
    fig = plt.figure()
    ax = fig.add_subplot(111)
    ax.set_aspect('equal')
    ax.get_xaxis().set_visible(False)
    ax.get_yaxis().set_visible(False)

    im = ax.imshow(np.random.rand(300,300),cmap='gray',interpolation='nearest')
    im.set_clim([0,1])
    fig.set_size_inches([5,5])


    #tight_layout()


    def update_img(n):
        tmp = np.random.rand(300,300)
        im.set_data(tmp)
        return im

    #legend(loc=0)
    ani = animation.FuncAnimation(fig,update_img,100,interval=30)
    writer = animation.writers['ffmpeg'](fps=30)

    ani.save('demo.mp4',writer=writer,dpi=dpi)
    return ani
```

I got the error as

Traceback (most recent call last):
  File "create_movie.py", line 37, in <module>
    ani_frame()
  File "create_movie.py", line 33, in ani_frame
    ani.save('demo.mp4',writer=writer,dpi=dpi)
  File "/home/lili/mc/envs/my_analysis/lib/python2.7/site-packages/matplotlib/animation.py", line 810, in save
    writer.grab_frame(*_savefig_kwargs)
  File "/home/lili/mc/envs/my_analysis/lib/python2.7/site-packages/matplotlib/animation.py", line 230, in grab_frame
    dpi=self.dpi, *_savefig_kwargs)
  File "/home/lili/mc/envs/my_analysis/lib/python2.7/site-packages/matplotlib/figure.py", line 1565, in savefig
    self.canvas.print_figure(_args, *_kwargs)
  File "/home/lili/mc/envs/my_analysis/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 196, in print_figure
    FigureCanvasAgg.print_figure(self, _args, *_kwargs)
  File "/home/lili/mc/envs/my_analysis/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2232, in print_figure
    **kwargs)
  File "/home/lili/mc/envs/my_analysis/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 519, in print_raw
    fileobj.write(renderer._renderer.buffer_rgba())
IOError: [Errno 32] Broken pipe

**Comment by tacaswell** [comment]
is ffmpeg installed?

**Comment by licode** [comment]
yes

**Comment by licode** [comment]
https://anaconda.org/mutirri/ffmpeg  for ffmpeg

**Comment by tacaswell** [comment]
There is not good error handling across the pipe, that error just means that ffmpeg croaked (for unclear reasons).

I would get it installed at the system level.  That package is 2 years old and complied against who know what other libraries.  Given the other ABI issues we have had my guess is that there is a segfault or some such going on.

Can you verify that running `ffmpeg` at the shell works as expected?

This code runs correctly on my system.

**Comment by licode** [comment]
good point. 
(my_analysis)lili@xf03idc-ws2:~/tomo_analysis$ ffmpeg
ffmpeg: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory

**Comment by tacaswell** [comment]
@ericdill Can you add ffmpeg to the list of things we built internally?

**Comment by ericdill** [comment]
This one? https://github.com/conda/conda-recipes/tree/master/ffmpeg

Oh neat that is @danielballan's recipe

**Comment by tacaswell** [comment]
I have no opinion as to which recipe to use.

**Comment by ericdill** [comment]
@danielballan can you give me some guidance here? I have never used ffmpeg and have no idea which recipe or version we should package internally

**Comment by danielballan** [comment]
Any version will be fine for our purposes. For Linux, the package in conda-recipes is fine.

**Comment by ericdill** [comment]
Thanks @danielballan . fingers crossed it will be easy to get building internally.

**Comment by ericdill** [comment]
Ok so I have ffmpeg building internally. I guess you can just do `conda install -c nsls2-tag ffmpeg` and see if it fixes this problem?
